Личный проект: генератор публикаций
htmlacademy-nodejs/147647-typoteka-3 pull request #3
Opened 2021-11-10 23:54 UTC by gyxman

2021-11-14 02:04 UTC, Krabaton requested changes

2021-11-14 02:04 UTC, Krabaton commented on src/service/cli/generate.js
> +  const threeMonthAgo = today.setMonth(today.getMonth() - 3);
Почему минус 3? Что такое 3?
Это к тому, что не надо магических чисел, лучше назвать переменную и вычитать уже ее.

2021-11-14 02:04 UTC, Krabaton commented on src/service/cli/generate.js
> +      return console.error('Не больше 1000 публикаций');
Убрать хардкод. Подставить шаблонную строку и значение переменной MAX_COUNT. Проверить все lint - везде должны быть шаблонные строки

2021-11-15 23:24 UTC, gyxman commented on src/service/cli/generate.js
> +  const threeMonthAgo = today.setMonth(today.getMonth() - 3);
поправил

2021-11-15 23:26 UTC, gyxman commented on src/service/cli/generate.js
> +      return console.error('Не больше 1000 публикаций');
поправил

2021-11-16 10:05 UTC, merged